version: '3.8'

services:
  telegram_bot_recognizer:
    container_name: telegram-bot-recognizer
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      "python", "run_bot.py"
    ]

